# Generated by Django 4.2.3 on 2023-10-19 06:07

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, upload_to=pathlib.PureWindowsPath('C:/Users/thisi/OneDrive/Desktop/compress'))),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
